export const MOCK_RESTAURANTS = [
	{
		id: 1,
		name: "McDonald's",
		category: "Fast Food",
		distance: 0.3,
		address: "123 Main St",
		rating: 3.8,
	},
	{
		id: 2,
		name: "Burger King",
		category: "Fast Food",
		distance: 0.7,
		address: "456 Oak Ave",
		rating: 3.5,
	},
	{
		id: 3,
		name: "Wendy's",
		category: "Fast Food",
		distance: 1.2,
		address: "789 Pine Rd",
		rating: 3.9,
	},
	{
		id: 4,
		name: "Taj Palace",
		category: "Indian",
		distance: 0.9,
		address: "321 Elm St",
		rating: 4.6,
	},
	{
		id: 5,
		name: "Spice Garden",
		category: "Indian",
		distance: 2.1,
		address: "654 Maple Dr",
		rating: 4.4,
	},
	{
		id: 6,
		name: "Golden Dragon",
		category: "Chinese",
		distance: 1.4,
		address: "987 Cedar Ln",
		rating: 4.2,
	},
	{
		id: 7,
		name: "Panda Express",
		category: "Chinese",
		distance: 0.5,
		address: "147 Birch Blvd",
		rating: 3.7,
	},
	{
		id: 8,
		name: "Chipotle",
		category: "Mexican",
		distance: 0.6,
		address: "258 Walnut Way",
		rating: 4.0,
	},
	{
		id: 9,
		name: "Taco Bell",
		category: "Mexican",
		distance: 1.1,
		address: "369 Spruce St",
		rating: 3.4,
	},
	{
		id: 10,
		name: "Olive Garden",
		category: "Italian",
		distance: 1.8,
		address: "741 Ash Ave",
		rating: 4.1,
	},
	{
		id: 11,
		name: "Domino's Pizza",
		category: "Pizza",
		distance: 0.4,
		address: "852 Poplar Pl",
		rating: 3.6,
	},
	{
		id: 12,
		name: "Pizza Hut",
		category: "Pizza",
		distance: 0.9,
		address: "963 Willow Way",
		rating: 3.8,
	},
];

export type Restaurant = (typeof MOCK_RESTAURANTS)[number];
